AWSTemplateFormatVersion: "2010-09-09"
Description: Application Load Balancer

Resources:
  ALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: devops-app-alb
      Scheme: internet-facing
      Subnets:
        - subnet-0a77027889b9e7edf  # us-east-1a (vpc-09c03efee4b2d68d2)
        - subnet-0235af0256cd6dd60  # us-east-1b (vpc-09c03efee4b2d68d2)
      SecurityGroups:
        - sg-0b7acf827bde090a1    # Replace this with actual valid SG ID
      Type: application

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: 80
      Protocol: HTTP
      VpcId: vpc-09c03efee4b2d68d2
      TargetType: ip

  Listener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ALB
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup

Outputs:
  ALBName:
    Description: Name of the created ALB
    Value: !GetAtt ALB.LoadBalancerName
