AWSTemplateFormatVersion: "2010-09-09"
Description: Application Load Balancer

Resources:
  ALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: devops-app-alb
      Scheme: internet-facing
      Subnets:
        - subnet-12345678  # Replace
        - subnet-87654321
      SecurityGroups:
        - sg-12345678      # Replace
      Type: application

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: 80
      Protocol: HTTP
      VpcId: vpc-12345678  # Replace
      TargetType: ip

  Listener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ALB
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup

Outputs:
  ALBName:
    Value: !Ref ALB
