AWSTemplateFormatVersion: "2010-09-09"
Description: Create a versioned S3 bucket

Resources:
  AppBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: my-devops-sample-bucket
      VersioningConfiguration:
        Status: Enabled

Outputs:
  BucketName:
    Value: !Ref AppBucket
